#!/usr/bin/env python

import json

def run(json_file):
    
    # Read configuration infomation
    with open(json_file,'r') as fh:
        config = json.load(fh)
    
    # Get the input json file
    input_file = config['args']['file']
    input_path = "{}/{}".format(config['PATHS']['OUTPUT_DIR'],config['args']['file'])
    with open(input_path,'r') as fh:
        json_data = json.load(fh)

    # Rewrite the input json file
    with open(input_path,'w') as fh:
        fh.write(json.dumps(json_data,indent=4,sort_keys=True))

if __name__ == "__main__":
    import sys
    run(sys.argv[1]);
